# -- BOT CONFIG --
BOT_TOKEN = ''
DEVELOPERID =
ADMIN =

# -- Redis Config --
REDIS_PORT = 6379
REDIS_HOST = 'localhost'
REDIS_DB = 4
REDIS_PASSWORD = None

# -- MARIADB CONFIG --
MARIADB_USER = ''
MARIADB_HOST = ''
MARIADB_PASSWORD = ''
MARIADB_DATABASE = ''
